### ISSUE TITLE
[API] new endpoint for Düsseldorf

### ISSUE THREAD

**Issue by ManAnRuck** [OParl/resources#2]
Düsseldorf have now also an Oparl endpoint, but missing in the endpoint api.

Links:
https://opendata.duesseldorf.de/dataset/oparl-schnittstelle-zum-ratsinformationsystem-der-stadt-düsseldorf
https://ris-oparl.itk-rheinland.de/Oparl/bodies/0015

**Comment by eFrane** [comment]
Transferred, as endpoints are collected in this repo.

**Comment by stv0g** [comment]
This issue can be closed
