### ISSUE TITLE
Add cc-egov/sternberg endpoints

### ISSUE THREAD

**Issue by konstin** [OParl/resources#5]
The following endpoints exist but aren't tracked yet

## cc-egov
https://www.algermissen.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.hagenbach.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.harsum.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.itzstedt.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.rosbach.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.trave.sitzung-online.de/bi/oparl/1.0/system.asp
https://ratsinfo.braunschweig.de/bi/oparl/1.0/system.asp

## sternberg

https://badpyrmont.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://emsdetten.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://enger.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://gronau.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://herford.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://hiddenhausen.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://kirchlengern.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://ladbergen.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://lohfelden.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://ratsinfo.aldenhoven.de/webservice/oparl/v1.0/system
https://ratsinfo.bad-muenstereifel.de/webservice/oparl/v1.0/system
https://ratsinfo.bruehl.de/webservice/oparl/v1.0/system
https://ratsinfo.langenberg.de/webservice/oparl/v1.0/system
https://ratsinfo.rheda-wiedenbrueck.de/webservice/oparl/v1.0/system
https://ratsinfo.stadt-kerpen.de/webservice/oparl/v1.0/system
https://ratsinfo.wesseling.de/webservice/oparl/v1.0/system
https://rim.ekom21.de/coelbe/webservice/oparl/v1.0/system
https://rim.ekom21.de/ehringshausen/webservice/oparl/v1.0/system
https://rim.ekom21.de/eschwege/webservice/oparl/v1.0/system
https://rim.ekom21.de/fernwald/webservice/oparl/v1.0/system
https://rim.ekom21.de/glashuetten/webservice/oparl/v1.0/system
https://rim.ekom21.de/grossalmerode/webservice/oparl/v1.0/system
https://rim.ekom21.de/hessisch-lichtenau/webservice/oparl/v1.0/system
https://rim.ekom21.de/homberg-efze/webservice/oparl/v1.0/system
https://rim.ekom21.de/ortenberg/webservice/oparl/v1.0/system
https://rim.ekom21.de/waldbrunn/webservice/oparl/v1.0/system
https://ris.wachtendonk.de/webservice/oparl/v1.0/system
https://roedinghausen.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://schiffdorf.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://sdnetrim.kdvz-frechen.de/rim4800/webservice/oparl/v1.0/system
https://sitzungsdienst.kdz-ws.net/gkz330/webservice/oparl/v1.0/system
https://spenge.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://stemwede.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://vlotho.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://wallenhorst.ratsinfomanagement.net/webservice/oparl/v1.0/system

**Comment by hejjoe** [comment]
https://www.algermissen.sitzung-online.de/bi/oparl/1.0/system.asp (http404?!)
https://www.wikidata.org/wiki/Q574412
https://www.openstreetmap.org/relation/91859

https://www.hagenbach.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q511139
https://www.openstreetmap.org/relation/904762

https://www.harsum.sitzung-online.de/bi/oparl/1.0/system.asp 69785
https://www.wikidata.org/wiki/Q531536
https://www.openstreetmap.org/relation/69785

https://www.itzstedt.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q544037
https://www.openstreetmap.org/relation/442744

https://www.rosbach.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q621237
https://www.openstreetmap.org/relation/450122

https://www.trave.sitzung-online.de/bi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q480062
https://www.openstreetmap.org/relation/442911

https://ratsinfo.braunschweig.de/bi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q2773
https://www.openstreetmap.org/relation/62531


sternberg

https://badpyrmont.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q556352
https://www.openstreetmap.org/relation/1184314

https://emsdetten.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q31995364
https://www.openstreetmap.org/relation/155714

https://enger.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q53901
https://www.openstreetmap.org/relation/147441

https://gronau.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q6924
https://www.openstreetmap.org/relation/162865

https://herford.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q3971
https://www.openstreetmap.org/relation/146654

https://hiddenhausen.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q53908
https://www.openstreetmap.org/relation/147443

https://kirchlengern.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q53911
https://www.openstreetmap.org/relation/12577782

https://ladbergen.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q181877
https://www.openstreetmap.org/relation/155443

https://lohfelden.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q562032
https://www.openstreetmap.org/relation/1115032

https://ratsinfo.aldenhoven.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q199968
https://www.openstreetmap.org/relation/158407

https://ratsinfo.bad-muenstereifel.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q241450
https://www.openstreetmap.org/relation/158145

https://ratsinfo.bruehl.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q7036
https://www.openstreetmap.org/relation/168481

https://ratsinfo.langenberg.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q225055
https://www.openstreetmap.org/relation/78566

https://ratsinfo.rheda-wiedenbrueck.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q6896
https://www.openstreetmap.org/relation/78727

https://ratsinfo.stadt-kerpen.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q3959
https://www.openstreetmap.org/relation/168483

https://ratsinfo.wesseling.de/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q14956
https://www.openstreetmap.org/relation/168448

https://rim.ekom21.de/coelbe/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q560951
https://www.openstreetmap.org/relation/225490

https://rim.ekom21.de/ehringshausen/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q633810
https://www.openstreetmap.org/relation/215976

https://rim.ekom21.de/eschwege/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q1468
https://www.openstreetmap.org/relation/549419

https://rim.ekom21.de/fernwald/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q625773
https://www.openstreetmap.org/relation/418621

https://rim.ekom21.de/glashuetten/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q637032
https://www.openstreetmap.org/relation/418290

https://rim.ekom21.de/grossalmerode/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q538635
https://www.openstreetmap.org/relation/549413

https://rim.ekom21.de/hessisch-lichtenau/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q558563
https://www.openstreetmap.org/relation/549417

https://rim.ekom21.de/homberg-efze/webservice/oparl/v1.0/system
https://www.wikidata.org/wiki/Q558616
https://www.openstreetmap.org/relation/452196

https://rim.ekom21.de/ortenberg/webservice/oparl/v1.0/system
https://rim.ekom21.de/waldbrunn/webservice/oparl/v1.0/system
https://ris.wachtendonk.de/webservice/oparl/v1.0/system
https://roedinghausen.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://schiffdorf.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://sdnetrim.kdvz-frechen.de/rim4800/webservice/oparl/v1.0/system
https://sitzungsdienst.kdz-ws.net/gkz330/webservice/oparl/v1.0/system
https://spenge.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://stemwede.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://vlotho.ratsinfomanagement.net/webservice/oparl/v1.0/system
https://wallenhorst.ratsinfomanagement.net/webservice/oparl/v1.0/system
