### ISSUE TITLE
Add more districts of Berlin

### ISSUE THREAD

**Issue by hejjoe** [OParl/resources#7]
Lichtenberg 
https://www.sitzungsdienst-lichtenberg.de/oi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q1007979

Marzahn-Hellerdorf
https://www.sitzungsdienst-marzahn-hellersdorf.de/oi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q119284

Pankow 
https://www.sitzungsdienst-pankow.de/oi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q163012

Treptow-Köpenick 
https://www.sitzungsdienst-treptow-koepenick.de/oi/oparl/1.0/system.asp
https://www.wikidata.org/wiki/Q158089

Source: https://daten.berlin.de/tags/allris

**Comment by eFrane** [comment]
Thanks a lot!

**Comment by hejjoe** [comment]
Thank you for implementing the issue that fast :)
